---
- name: Backup Ignition Projects
  hosts: backup_repositories
  tasks:
    - name: Create Backup Directories
      file:
        path: "{{ backup_directory }}/{{ item.ignition_server }}"
        state: directory
      with_items: "{{ ignition_servers }}"
    - include: tasks/backup-ignition.yml
      with_items: "{{ ignition_servers }}"

